:apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.deployment.name }}
    namespace: {{ .Values.namespace }}
    labels:
       app: locanta
       type: locanta-dep
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.deployment.pod.labels | nindent 8 }}
  template:
    metadata:
      labels:
	date: "{{ now | unixEpoch }}"
        {{- toYaml .Values.deployment.pod.labels | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.deployment.pod.image}}
        name:  {{ .Values.deployment.pod.name}}
        imagePullPolicy: Always
        env:
        {{- toYaml .Values.deployment.pod.env | nindent 10 }}
