replicaCount: 2
feReplicaCount: 1
servicePort: 8080
beServiceName: menuserver-be-service
namespace: default
bePorts:
  - port: 8888
    targetPort: 8080
fePorts:
  - port: 8888
    targetPort: 3000
postgresql:
  postgresqlUsername: postgres
  postgresqlDatabase: postgres
  #postgresqlPassword: "123456"